---
- name: restart apache
  service: 
    name=httpd
    state=restarted

- name: Generate SSL
  command: openssl genrsa -out "/var/www/ssl/{{ item }}.key" 1024
  with_items: "{{ web_domain }}"
  ignore_errors: yes
  tags: Create SSL for Web
  notify: Generate CSR

- name: Generate CSR
  command: openssl req -new -sha256 -subj '/CN={{ item }}' -key "/var/www/ssl/{{ item }}.key" -out "/var/www/ssl/{{ item }}.csr"
  with_items: "{{ web_domain }}"
  ignore_errors: yes
  notify: Generate Self-signed Certificate
  tags: Create SSL for Web

- name: Generate Self-signed Certificate
  command: openssl req -x509 -days 1825 -key "/var/www/ssl/{{ item }}.key" -in "/var/www/ssl/{{ item }}.csr" -out "/var/www/ssl/{{ item }}.crt"
  with_items: "{{ web_domain }}"
  ignore_errors: yes
  tags: Create SSL for Web
  notify: restart apache
