---
- name: Check if Gluster volumes already exist.
  shell: "gluster volume info"
  changed_when: false
  register: gluster_volume_info
  tags: Add gluster volume

- name: Create Brick directory
  file:
    path: "{{ item.brick_path }}"
    state: directory
    owner: root
    group: root
    mode: "u+rwx,g+rwx,o+rwx"
  with_items: "{{ volumes }}"
  tags: Add gluster volume

- name: Start glusterd on the nodes if not already started
  service:
       state: started
       name: glusterd
       enabled: yes
  delegate_to: "{{ item }}"
  run_once: true
  with_items: "{{ groups.storage_srv }}"
  tags: Add gluster volume

- name: create gluster volume
  gluster_volume:
    state: "{{ gluster_cluster_state | default('present') }}"
    volume: "{{ item.name }}"
    bricks: "{{ item.brick_path }}"
    replicas: "{{ item.replicas | default(0) }}"
    arbiters: "{{ item.arbiters | default(0)}}"
    disperses: "{{ item.disperses | default(0) }}"
    redundancies: "{{ item.redundancies | default(0) }}"
    force: "{{ item.force | default('no') }}"
    options: "{{ item.options | default({}) }}"
    cluster: "{{ groups.storage_srv | join(',') }}"
    directory: "{{ item.limit_path | default('/')}}"
    quota: "{{ item.volume_limit | default('10GB') }}"
  run_once: true
  with_items: "{{ volumes }}"
  tags: Add gluster volume

- name: Create Brick directory
  file:
    path: "{{ item.brick_path }}"
    state: directory
    owner: root
    group: root
    mode: "u+rwx,g+rwx,o+rwx"
  with_items: "{{ volumes }}"
  tags: Add gluster volume
