---
# handlers file for ActiveDirectory
- name: server reboot
  command: /sbin/shutdown -r +0
  async: 0
  poll: 0
  ignore_errors: true
  tags: reboot
  notify: Waiting for server to come after reboot

- name: Waiting for server to come after reboot
  local_action:
    wait_for host={{ ansible_ssh_host }}
    state=started
    port=22
    delay=30
    timeout=300
    connect_timeout=15
  tags: reboot

