---
- name: Install Epel release
  yum:
    name: epel-release
    state: latest
  tags: basic-tasks


- name: Update sytem kernel and packages
  yum:
    name: '*'
    state: latest
  tags: basic-tasks

- name: Install basic utils
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
   - "{{ basic_utils }}"
  tags: basic-tasks
  notify: server reboot

