- hosts: storage_client
  roles:
  - role: glusterclient
    volumes:
    - name: docker-registry
      dst_point: /mnt
      mount_type: glusterfs
    - name: test
      dst_point: /mnt
      mount_type: glusterfs
    storage_VIP_ip: 192.168.36.7
  serial: "100%"
