- name: upgrade kubeadm
  yum:
    name: kubeadm
    state: "{{kubeadm_version}}"
    
- name: pip install pexpect
  pip:
    name: pexpect

- name: Run kubeadm upgrade
  expect:
    command: kubeadm upgrade apply {{upgrade_version}}
    echo: yes
    timeout: 250
    responses:
      upgrade?: "y"
