---
- name: Add GlusterFS repository
  yum_repository:
    name: Glusterfs
    description: CentOS-$releasever - Gluster
    baseurl: http://mirror.centos.org/centos/$releasever/storage/$basearch/gluster-6
    enabled: yes
    gpgcheck: no
  tags: Install and start GlusterServer

- name: Install GlusterFS Server
  yum:
    name: glusterfs-client 
    state: latest
  with_items:
    - glusterfs-client
    - glusterfs-fuse
    - glusterfs-rdma
  tags: Install and start GlusterServer
