---
- name: restart nginx
  service:
    name=nginx
    state=restarted

- name: Generate key
  command: openssl genrsa -out "/etc/nginx/ssl/{{ item }}.key" 1024
  with_items: "{{ web_domain }}"
  ignore_errors: yes
  tags: Create SSL for Web
  notify: Generate CSR

- name: Generate CSR
  command: openssl req -new -sha256 -subj '/CN={{ item }}' -key "/etc/nginx/ssl/{{ item }}.key" -out "/etc/nginx/ssl/{{ item }}.csr"
  with_items: "{{ web_domain }}"
  ignore_errors: yes
  notify: Generate Self-signed Certificate
  tags: Create SSL for Web

- name: Generate Self-signed Certificate
  command: openssl req -x509 -days 1825 -key "/etc/nginx/ssl/{{ item }}.key" -in "/etc/nginx/ssl/{{ item }}.csr" -out "/etc/nginx/ssl/{{ item }}.crt"
  with_items: "{{ web_domain }}"
  ignore_errors: yes
  tags: Create SSL for Web
  notify: restart nginx

