apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
kubernetesVersion: {{kubernetes_version}}
networking:
  podSubnet: {{pod_network_cidr}}
{% if groups["k8s-masters"] | length > 1 %}
apiServerCertSANs:
{% if virtual_ip is defined %}
- {{virtual_ip}}
{% endif %}
{% for master in groups["k8s-masters"] %}
- {{hostvars[master]['ansible_usehost']}}
{% endfor %}
- localhost
{% endif %}
etcd:
  endpoints:
  - https://localhost:{{etcd_proxy_port}}
{% for master in groups["k8s-masters"] %}
  - https://{{hostvars[master]['ansible_usehost']}}:2379
{% endfor %}
  caFile: /etc/kubernetes/pki/etcd/ca.pem
  certFile: /etc/kubernetes/pki/etcd/client.pem
  keyFile: /etc/kubernetes/pki/etcd/client-key.pem
apiServerExtraArgs:
  endpoint-reconciler-type: lease
imageRepository: {{docker_registry| trim}}/kubernetes