---
- name: Update MySQL root password for all root accounts
  mysql_user: 
    name: root 
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    state: present
  with_items:
     - "{{ ansible_hostname }}"
     - 127.0.0.1
     - ::1
     - localhost
  tags: Basic MySql configuration

- name: Allow root connect to mysql without password from localhost
  template:
    src: "root.cnf.j2"
    dest: "/root/.my.cnf"
    owner: root
    group: root
    mode: 0600
  tags: Basic MySql configuration

- name: Delete Anonimous user 
  mysql_user: 
    name: '' 
    host: "{{ item }}"
    state: absent
  with_items:
    - localhost
    - "{{ ansible_hostname }}"
  tags: Basic MySql configuration

- name: Remove the test database
  mysql_db: 
    name: test 
    state: absent
  notify: restart mysqld daemon
  tags: Basic MySql configuration
