- name: get epel
  get_url:
    url: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    dest: /tmp/epel-release-latest-7.noarch.rpm

- name: install epel
  become: yes
  yum: 
    name: /tmp/epel-release-latest-7.noarch.rpm
    state: present

- name: install docker dependencies
  become: yes
  yum:
    name: "{{item}}"
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - policycoreutils-python
    - python-pip
  tags: aaa

- name: install certain python modules for docker
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-py
  tags: aaa

- name: Installs docker
  yum: 
    name: docker-ce-{{docker_version}} # docker in some distros
    state: installed     

- name: restart docker
  systemd: 
    name: docker 
    state: restarted
    daemon_reload: yes
    enabled: yes
