- name: install httpd
  yum:
    name: httpd
    state: latest
  tags: intall and conf httpd

- name: Start and enable httpd
  service:
    name: httpd
    state: started
    enabled: yes
  tags: intall and conf httpd

- name: Copy mod_rpaf.rpm to backend
  copy:
     src: mod_rpaf.rpm
     dest: /tmp/mod_rpaf.rpm
  tags: intall and conf httpd

- name: Install mod_rpaf
  yum:
     name: /tmp/mod_rpaf.rpm
     state: present
  tags: intall and conf httpd

- name: Install mod_ssl
  yum:
     name: mod_ssl
     state: present
  tags: intall and conf httpd

